### ISSUE TITLE
[Feature Request] Enable cloud-based Model Optimization

### ISSUE THREAD

**Issue by larsll** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#10]
To improve the speed of loading models on the car it would be an idea to perform the Tensorflow -> OpenVINO model optimization in a lambda function, rather than on the car. This should save 15-20 seconds when loading a model on the car.

Initial concept (Docker file + conversion code) is here: https://github.com/aws-solutions-library-samples/guidance-for-aws-deepracer-event-management/pull/9

Design decisions needed:
* Where in the upload-pipeline should it happen? Two options
  * Instead of `clamscan_post`; trigger on virus scan complete, then optimize and upload to target location
  * After `clamscan_post`; when the model is Available (maybe trigger on the change in DynamoDB?)
* Is another status in the DynamoDB desired (Available -> Optimized?)
* If processing after `clamscan_post`: shall initial file be kept and new file in a new location, or shall it be edited in place?

**Comment by davidfsmith** [comment]
This change has now been merged in as part of PR #9
