### ISSUE TITLE
Raspberry Pi doesn't work on latest versions of Pi OS

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#56]
Using Raspberry Pi 4 Model B Pi OS v5.0 from October 2023 works fine.  When using Pi OS v5.2 from March 2024 laptimes cannot be registered.  Both versions for v18.18.0 of node.  Service is running on both and no obvious errors from journalctl.  Both access DREM via port 8080 fine and DREM reports that timer is online.

**Comment by davidfsmith** [comment]
Hi Mark,

We discovered this issue earlier this week and have updated the README to reflect the issue

> Please note that the most recent release of Raspberry Pi OS "Bookworm" is currently not supported, please use "Bullseye" (Legacy) for the RPi operating system.

The timing hat is not the only hat impacted by this issue.

As soon as we have a solution we'll post it up
