### ISSUE TITLE
Update instructions to include how to update and existing DREM environment

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#67]
The install instructions are clear on how to deploy a new instance of DREM, however they lack instructions on how to update.

**Comment by StevenAskwith** [comment]
Once you are on the github/pipeline based version of DREM (v2.6.0 and higher), new releases are dropped into the release/stable branch and your pipeline should automatically run on a new release, you simply have to "approve" the release in CodePipeline.

Your pipeline may "go to sleep" if it hasn't ran for a while, in which case click "Release change" on the pipeline to wake it up and deploy the latest version
