### ISSUE TITLE
Forever raceway cosmetic issue

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#77]
![image](https://github.com/user-attachments/assets/912b4e28-7113-4fdc-98c5-721d9530875f)
 @StevenAskwith yesterday's update added forever raceway but the format seems off when I pulled the update

**Comment by StevenAskwith** [comment]
That's a caching issue with your website/public/locales/en/translation.json.  i.e. CloudFront or your local cache has held onto the old version, wait for the TTL to expire and it should just update with no further action.
